services:
    spotify-release-list:
        # change <your-username> with your actual Github username
        image: ghcr.io/<your-username>/spotify-release-list-docker:latest
        container_name: spotify-release-list
        ports:
            - 80:80